name: deploy-tickets

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'tickets/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: build docker image
        run: cd tickets && docker build -t nicovui/tickets .
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push to docker hub
        run: docker push nicovui/tickets
      - name: initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: push to Digital Ocean kubenetes cluster
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: restart tickets deployment
        run: kubectl rollout restart deployment tickets-depl
